server:
  port: 8083
spring:
  application:
    name: carts-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/electronic_store_carts?useSSL=true&serverTimezone=UTC
    username: root
    password: 
    hikari:
      connection-timeout: 3000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka