server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/fdcend/electronic-strore
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}